config/routes.rb
Rails.application.routes.draw do
  get "password_resets/new"
  get "password_resets/edit"
  get "sessions/new"

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  root to: "static_pages#home"
  resources :contacts, only: %i[index create]

  get "/home", to: "static_pages#home"
  get "/about", to: "static_pages#about"
  get "/gallery", to: "static_pages#gallery"
  get "/gallery/:id", to: "static_pages#designs_detail"
  get "/faq", to: "static_pages#faq"
  # get "/contacts", to: "static_pages#contacts"

  get "/signup", to: "users#new"

  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
end

app/views/layouts/_footer.html.erb
<footer class = "footer">
<ul class="navbar__icons">
    <li>&copy;Copy Right 2010 TOKKI DESIGN</li>
    <li><i class="fab fa-twitter"></i></li>
    <li><i class="fab fa-facebook-f"></i></li>
   </ul>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar">
  <div class="navbar__logo">
    <div class="logo_set">
      <%= image_tag 'tkimg/tokki_black_small.png' %>
      <div class= "carrot"><i class="fas fa-carrot"></i></div>
    </div>
  </div>
  <ul class ="navbar__menu" >
    <li><%= link_to "Home",      root_path,   id: "logo_2"%></li>
    <li><%= link_to "About",     about_path , id: "logo_2"%></li>
    <li><%= link_to "Gallery",   gallery_path,id: "logo_2"%></li>
    <li><%= link_to "Faq",       faq_path,    id: "logo_2"%></li>
    <li><%= link_to "Contacts", contacts_path ,id: "logo_2"%></li>
    <% if logged_in? %>
      <li><%= link_to "Users", users_path ,id: "logo_2"%></li>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" id="logo_2">
          Account <b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
          <li><%= link_to "Profile", current_user %></li>
          <li><%= link_to "Settings", edit_user_path(current_user) %></li>
          <li>
            <%= link_to "Log out", logout_path, method: :delete %>
          </li>
        </ul>
      </li>
    <% else %>
      <li><%= link_to "Log in", login_path ,id: "logo_2"%></li>
      <li><%= link_to "Sign up", signup_path,  id: "logo_2"%></li>
    <% end %>
  </ul>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js"></script>
<![endif]-->
<meta charset="UTF-8">
<title>Tokki Design in Textile Industry</title>
<meta name="description" content="A Textile Degigner from Japan">
<meta name="description" content="Textile design","a skilled textile designer","translating Korean to Japanese">
<meta name="author" content="JY LEE">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<%= favicon_link_tag('tkimg/favicon.ico') %>
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.13.0/css/all.css" integrity="sha384-Bfad6CLCknfcloXFOyFnlgtENryhrpZCe29RTifKEixXQZ38WheV+i/6YWSzkz3V" crossorigin="anonymous">
<link href="https://fonts.googleapis.com/css2?family=Source+Sans+Pro:wght@600&display=swap" rel="stylesheet">

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <title><%= full_title(yield(:title)) %></title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag    'application', media: 'all','data-turbolinks-track': 'reload' %>
  <%= stylesheet_link_tag   'custom',      media: 'all','data-turbolinks-track': 'reload'  %> <!--unless controller_name == "static_pages"-->
  <%= javascript_pack_tag    'application', 'data-turbolinks-track': 'reload' %>
  <link rel="preconnect" href="https://fonts.gstatic.com">
  <link href="https://fonts.googleapis.com/css2?family=Italianno&display=swap" rel="stylesheet">
  <link rel="preconnect" href="https://fonts.gstatic.com">
  <link href="https://fonts.googleapis.com/css2?family=Calligraffitti&family=Indie+Flower&family=Princess+Sofia&family=Ravi+Prakash&family=Smythe&family=Spectral+SC:wght@200&display=swap" rel="stylesheet">
  <%= render 'layouts/shim' %>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container">
    <% flash.each do |message_type, message| %>
      <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
    <% end %>
    <%= yield %>
    <%= debug(params) if Rails.env.development? %>
  </div>
</body>
<%= render 'layouts/footer' %>
</html>